services:
  fide-api:
    network_mode: "host"
    container_name: fide-api
    image: python:3.12-alpine3.20
    working_dir: "/fide-api"
    stop_grace_period: 1s
    command: sh -c "pip install -r requirements.txt && uvicorn src.api:app --reload"
    volumes:
      - ./:/fide-api
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CACHE_EXPIRY=3600
      - MONGO_URI=mongodb://localhost:27017/
      - MONGO_DB=fide_api
      - MONGO_FIDE_COLLECTION=fide_ratings
      - MONGO_CFC_COLLECTION=cfc_ratings
      - FIDE_DOWNLOAD_URL=https://ratings.fide.com/download/standard_rating_list_xml.zip
      - CFC_DOWNLOAD_URL=https://www.chess.ca/wp-content/uploads/tdlist.txt
    depends_on:
      - redis
      - mongodb
      
  redis:
    image: redis:7-alpine
    container_name: fide-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning
    
  mongodb:
    image: mongo:6
    container_name: fide-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    command: mongod --quiet --logpath /dev/null

volumes:
  redis-data:
  mongodb-data:
