name: Docker Build and Deploy

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx for better caching and multi-platform support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata for the Docker image
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            # cd into the right directory
            cd ~/fide-api/ratings-api || exit 1

            # Debug - show what we're trying to pull
            echo "Repo owner: ${{ github.repository_owner }}"
            echo "Repo name: ${{ github.event.repository.name }}"
            
            # Get lowercase repository parts
            REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
            REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
            
            # Use the same format as in the build step
            IMAGE_PATH="ghcr.io/${REPO_OWNER}/${REPO_NAME}"
            echo "Will pull: ${IMAGE_PATH}:latest"
            
            # Login to GitHub Container Registry using PAT
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            
            # Pull the latest image
            docker pull ${IMAGE_PATH}:latest || {
              echo "Docker pull failed, proceeding with local image if available"
            }
            
            # Create or update docker compose.yml
            cat > ~/fide-api-docker-compose.yml << EOL
            services:
              fide-api:
                container_name: fide-api
                image: ${IMAGE_PATH}:latest
                restart: always
                ports:
                  - "8000:8000"
                environment:
                  - REDIS_HOST=redis
                  - REDIS_PORT=6379
                  - REDIS_DB=0
                  - CACHE_EXPIRY=3600
                  - MONGO_URI=${{ secrets.MONGODB_URI || 'mongodb://mongodb:27017/' }}
                  - MONGO_DB=fide_api
                  - FIDE_DOWNLOAD_URL=https://ratings.fide.com/download/standard_rating_list_xml.zip
                  - CFC_DOWNLOAD_URL=https://storage.googleapis.com/cfc-public/data/tdlist.txt
                depends_on:
                  - redis
                
              redis:
                image: redis:7-alpine
                container_name: fide-redis
                restart: always
                volumes:
                  - redis-data:/data
                command: redis-server --save 60 1 --loglevel warning

            volumes:
              redis-data:
            EOL
            
            # Check if docker-compose file was created correctly
            echo "Created docker-compose file:"
            cat ~/fide-api-docker-compose.yml
            
            # Run with docker-compose
            docker compose -f ~/fide-api-docker-compose.yml down || echo "No previous containers to remove"
            docker compose -f ~/fide-api-docker-compose.yml up -d
