name: Update Rating Lists

on:
  schedule:
    # Run on the 1st of every month at 2:00 AM UTC
    - cron: '0 2 1 * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-ratings:
    runs-on: ubuntu-latest
    
    steps:
    - name: SSH and run rating list update
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.HOST_KEY }}
        port: ${{ secrets.HOST_PORT }}
        script: |
          cd ~/fide-api/ratings-api
          docker exec fide-api python -c "
          import sys
          sys.path.append('/app')
          from src.scraper.ratinglists.updater import update_all_rating_lists
          print('Starting rating list update...')
          update_all_rating_lists()
          print('Rating list update completed!')
          "
        
    - name: Check for errors
      if: failure()
      run: |
        echo "Rating list update failed!"
        echo "Check the logs above for details."